# Generated by Django 5.0.6 on 2024-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketNews",
            fields=[
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("forex", "Forex"),
                            ("crypto", "Crypto"),
                            ("merger", "Merger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datetime", models.IntegerField()),
                ("headline", models.CharField(max_length=255)),
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.URLField()),
                ("related", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="StockRecommendation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stock", models.CharField(max_length=100)),
                ("confidence", models.IntegerField()),
                ("advice", models.CharField(max_length=50)),
            ],
        ),
    ]
