# Generated by Django 5.0.6 on 2024-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("forex", "Forex"),
                            ("crypto", "Crypto"),
                            ("merger", "Merger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datetime", models.IntegerField()),
                ("headline", models.CharField(max_length=255)),
                ("news_id", models.IntegerField(unique=True)),
                ("image", models.URLField()),
                ("related", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
    ]
