# Generated by Django 4.2.13 on 2024-06-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0005_remove_cache_key_alter_cache_id_alter_cache_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FilePathField(path='C:\\Users\\admin\\Desktop\\Software project\\i2024-03\\Backend\\trading\\media\\csv_files')),
            ],
        ),
    ]
