# Generated by Django 5.0.6 on 2024-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingbot", "0006_csvfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="csvfile",
            name="file_path",
            field=models.FilePathField(
                path="C:\\Tradingpro\\i2024-03\\Backend\\trading\\media\\csv_files"
            ),
        ),
    ]
