# Generated by Django 5.0.6 on 2024-07-02 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tradingbot", "0008_stockrecommendation_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cache",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cache",
            name="expires_at",
        ),
    ]
