# Generated by Django 5.0.6 on 2024-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingbot", "0010_trade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="price",
        ),
        migrations.AddField(
            model_name="trade",
            name="currentPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="entryPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
