name: Java Spring Boot and React CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build Backend with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Build Docker Images
      run: |
        docker build -t my-backend:latest ./backend
        docker build -t my-frontend:latest ./frontend

    - name: Push Docker Images to Registry
      run: |
        echo "Push images to Docker registry here"

    - name: Deploy to VDS
      run: |
        echo "Commands to deploy application to your VDS"
